import { cn } from "@/src/utils/cn";

const shadowClasses = cn([
  "shadow-lg",
  "shadow-melon-light",
  "hover:shadow-md",
  "active:shadow-sm",
  "dark:shadow-charcoal-blue-dark",
]);

export const classnames = {
  root: cn([
    "relative",
    "inline-flex",
    "items-center",
    "justify-center",
    "gap-2",
    "whitespace-nowrap",
    "rounded-md",
    "text-base",
    "font-medium",
    "font-button",
    "transition-all",
    "scale-100",
    "transition",
    "duration-300",
    "ease-in-out-cubic",
    "focus-visible:outline-none",
    "focus-visible:ring-1",
    "focus-visible:ring-ring",
    "active:scale-[0.98]",
    "active:border-none",
    "disabled:pointer-events-none",
    "disabled:opacity-50",
    "[&_svg]:pointer-events-none",
    "[&_svg]:size-4",
    "[&_svg]:shrink-0",
  ]),
  size: {
    example: cn(["px-5", "py-3"]),
    sm: cn(["h-9", "px-3", "text-sm"]),
    default: cn(["h-12", "px-5"]),
    lg: cn(["h-14", "px-7", "text-[1.125rem]"]),
    icon: cn(["h-9 w-9"]),
  },
  variant: {
    default: cn([
      "bg-primary",
      "text-white",
      "hover:bg-primary-hover",
      "dark:bg-primary-dark",
      "dark:text-charcoal-blue",
      "dark:hover:bg-primary-dark-hover",
      "dark:hover:text-white",
      shadowClasses,
    ]),
    secondary: cn([
      "bg-secondary",
      "text-white",
      "hover:bg-secondary-hover",
      "dark:bg-secondary-dark",
      "dark:hover:bg-secondary-dark-hover",
      shadowClasses,
    ]),
    destructive: cn(["bg-destructive", "text-white", "hover:bg-destructive-hover", shadowClasses]),
    outline: cn([
      "bg-transparent",
      "text-secondary",
      "border-[1.5px]",
      "border-secondary",
      "hover:bg-secondary",
      "hover:text-white",
      "dark:text-primary-dark",
      "dark:border-primary-dark",
      "dark:hover:bg-primary-dark",
      "dark:hover:text-charcoal-blue",
    ]),
    ghost: cn([
      "bg-ghost",
      "text-salmon",
      "font-semibold",
      "hover:bg-ghost-hover",
      "hover:text-white",
      "dark:bg-ghost-dark",
      "dark:text-white",
      "dark:hover:bg-ghost-dark-hover",
    ]),
    link: cn([
      "!px-0",
      "bg-transparent",
      "text-primary",
      "font-bold",
      "rounded-none",
      "transition-none",
      "hover:text-rose",
      "hover:underline",
      "dark:text-white",
      "dark:hover:text-primary-dark",
    ]),
  },
};
