import { cn } from "@/src/utils/cn";

/**
 * @const classnames
 */
export const classnames = {
  content: cn([
    "group/featured-post",
    "mb-4",
    "font-medium",
    "text-[15px]",
    "text-[hsl(11,20%,25%)]",
    "transition-all",
    "duration-300",
    "ease-in-out-cubic",
    "dark:text-[hsl(258,26%,80%)]",
    "group-hover/featured-post:text-[hsl(11,20%,10%)]",
    "group-hover/featured-post:dark:text-white",
  ]),
  footer: cn(["group/featured-post", "overflow-hidden"]),
  link: {
    icon: cn([
      "group/featured-post",
      "ml-0",
      "transition-all",
      "duration-300",
      "ease-in-out-cubic",
      "group-hover/featured-post:ml-1",
    ]),
    text: cn([
      "group/featured-post",
      "flex",
      "items-center",
      "space-x-1",
      "font-bold",
      "text-rose",
      "opacity-0",
      "translate-y-10",
      "transition-all",
      "duration-300",
      "ease-in-out-cubic",
      "dark:text-tropical-indigo",
      "group-hover/featured-post:opacity-100",
      "group-hover/featured-post:translate-y-0",
    ]),
  },
  root: cn([
    "group/featured-post",
    "flex",
    "flex-col",
    "scale-100",
    "transition-all",
    "duration-300",
    "ease-in-out-cubic",
    "group-hover/featured-post:scale-105",
  ]),
  thumbnail: cn([
    "group/featured-post",
    "flex",
    "items-center",
    "justify-center",
    "overflow-hidden",
    "mb-4",
    "h-[200px]",
    "rounded-lg",
    "scale-100",
    "shadow-lg",
    "shadow-theme-light",
    "transition-all",
    "duration-300",
    "ease-in-out-cubic",
    "dark:shadow-theme-dark",
    "group-hover/featured-post:scale-105",
    "group-active/featured-post:scale-100",
  ]),
  thumbnailImg: cn(["group/featured-post", "scale-100", "transition-all", "duration-300", "ease-in-out-cubic", "group-hover/featured-post:scale-110"]),
  title: cn(["group/featured-post", "mb-3", "font-lg", "font-bold", "font-heading", "text-2xl"]),
  topic: {
    text: cn([
      "group/featured-post",
      "font-bold",
      "text-sm",
      "text-tree-bark",
      "uppercase",
      "transition-all",
      "duration-300",
      "ease-in-out-cubic",
      "dark:text-tropical-indigo",
      "group-hover/featured-post:text-rose",
      "group-hover/featured-post:dark:text-tropical-indigo",
    ]),
    wrapper: cn(["group/featured-post", "mb-2", "bg-transparent"]),
  },
};